export const tempNoteListData = [
  { name: "남수오", bookCoverImage: "📘" },
  { name: "남지오", bookCoverImage: "📕" },
  { name: "손고운", bookCoverImage: "📙" },
  { name: "남원일", bookCoverImage: "📓" },
  { name: "임태완", bookCoverImage: "📒" },
  { name: "임유빈", bookCoverImage: "📔" },
  { name: "장운진", bookCoverImage: "📓" },
  { name: "황인택", bookCoverImage: "📕" },
  { name: "김종민", bookCoverImage: "📘" },
  { name: "한경훈", bookCoverImage: "📙" },
  { name: "남수오", bookCoverImage: "📘" },
  { name: "남지오", bookCoverImage: "📕" },
  { name: "손고운", bookCoverImage: "📙" },
  { name: "남원일", bookCoverImage: "📓" },
  { name: "임태완", bookCoverImage: "📒" },
  { name: "임유빈", bookCoverImage: "📔" },
  { name: "장운진", bookCoverImage: "📓" },
  { name: "황인택", bookCoverImage: "📕" },
  { name: "김종민", bookCoverImage: "📘" },
  { name: "한경훈", bookCoverImage: "📙" },
  { name: "남수오", bookCoverImage: "📘" },
  { name: "남지오", bookCoverImage: "📕" },
  { name: "손고운", bookCoverImage: "📙" },
  { name: "남원일", bookCoverImage: "📓" },
  { name: "임태완", bookCoverImage: "📒" },
  { name: "임유빈", bookCoverImage: "📔" },
  { name: "장운진", bookCoverImage: "📓" },
  { name: "황인택", bookCoverImage: "📕" },
  { name: "김종민", bookCoverImage: "📘" },
  { name: "한경훈", bookCoverImage: "📙" },
  { name: "남수오", bookCoverImage: "📘" },
  { name: "남지오", bookCoverImage: "📕" },
  { name: "손고운", bookCoverImage: "📙" },
  { name: "남원일", bookCoverImage: "📓" },
  { name: "임태완", bookCoverImage: "📒" },
  { name: "임유빈", bookCoverImage: "📔" },
  { name: "장운진", bookCoverImage: "📓" },
  { name: "황인택", bookCoverImage: "📕" },
  { name: "김종민", bookCoverImage: "📘" },
  { name: "한경훈", bookCoverImage: "📙" },
  { name: "남수오", bookCoverImage: "📘" },
  { name: "남지오", bookCoverImage: "📕" },
  { name: "손고운", bookCoverImage: "📙" },
  { name: "남원일", bookCoverImage: "📓" },
  { name: "임태완", bookCoverImage: "📒" },
  { name: "임유빈", bookCoverImage: "📔" },
  { name: "장운진", bookCoverImage: "📓" },
  { name: "황인택", bookCoverImage: "📕" },
  { name: "김종민", bookCoverImage: "📘" },
  { name: "한경훈", bookCoverImage: "📙" },
];
